# Generated by Django 4.2.17 on 2024-12-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_tag_unique_tags_remove_tag_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_url',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Короткий код'),
        ),
    ]
