# Generated by Django 4.2.17 on 2024-12-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_recipe_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_url',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
