version: '3'

volumes:
  static:
  media:
  postgres_data:

services:
  db:
    platform: linux/amd64
    image: postgres:13.0
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  frontend:
    container_name: foodgram-frontend
    image: stxxxx/foodgram_front:latest
    restart: always
    env_file: ../.env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend

  backend:
    container_name: foodgram-backend
    image: stxxxx/foodgram_back:latest
    restart: always
    env_file: ../.env
    volumes:
      - static:/app/collected_static
      - media:/app/media
    depends_on:
      - db

  nginx:
    image: nginx:1.23.3-alpine
    restart: always
    ports:
      - 7000:80
    volumes:
      - static:/staticfiles/
      - media:/app/media
    depends_on:
      - frontend
